#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

# shellcheck disable=SC2154
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if [ ! -d "$HOME/.bin/" ]; then
  mkdir "$HOME/.bin"
fi

HOMEBREW_PREFIX="/usr/local"

if [ -d "$HOMEBREW_PREFIX" ]; then
  if ! [ -r "$HOMEBREW_PREFIX" ]; then
    sudo chown -R "$LOGNAME:admin" /usr/local
  fi
else
  sudo mkdir "$HOMEBREW_PREFIX"
  sudo chflags norestricted "$HOMEBREW_PREFIX"
  sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
fi

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
    curl -fsS \
      'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

    export PATH="/usr/local/bin:$PATH"
fi

if brew list | grep -Fq brew-cask; then
  fancy_echo "Uninstalling old Homebrew-Cask ..."
  brew uninstall --force brew-cask
fi

DOCKER_VERSION=""

if command -v docker; then
  DOCKER_VERSION='$(docker -v)'
fi

# Kill Docker Toolbox
case "$DOCKER_VERSION" in
  Docker\ version\ 1.11.*)
    echo "Uninstalling Docker Toolbox"
    docker-machine rm default
    rm /usr/local/bin/docker
    rm /usr/local/bin/docker-compose
    rm /usr/local/bin/docker-machine

    if [ -d "$HOME/.docker" ]; then
      rm -rf "$HOME/.docker"
    fi

    if [ -d "/Applications/Docker" ]; then
      rm -rf "/Applications/Docker"
    fi
    ;;
esac

fancy_echo "Updating Homebrew formulae ..."
brew update
brew bundle --file=- <<EOF
tap "thoughtbot/formulae"
tap "homebrew/versions"
tap "homebrew/dupes"
tap "homebrew/homebrew-php"

# Unix
brew "git"
brew "git-flow"
brew "htop-osx"
brew "vim"
brew "bash-completion"
brew "fish"
brew "tmux"
brew "wget"

# Programming languages
brew "node4-lts"

# Misc
brew "brew-php-switcher"
brew "nvm"
brew "mcrypt"

# Apps
brew "kdiff3"
EOF

brew install php56 --with-mysql --with-pqsql --with-intl
brew-php-switcher 56 -s

# Setup for investability
if [ ! -d "$HOME/Dev/" ]; then
  mkdir "$HOME/Dev"
fi

IA_HOSTS_ENTRY="127.0.0.1 i2.local i2local_mysql-investability i2local_redis_1 i2local_elasticsearch_1"

if [ -n "$(grep -q '$IA_HOSTS_ENTRY' /etc/hosts)" ]; then
  echo "Adding $IA_HOSTS_ENTRY to your /etc/hosts file"
  sudo -- sh -c -e "echo '$IA_HOSTS_ENTRY' >> /etc/hosts";
fi

if [ -f "$HOME/.laptop.local" ]; then
  fancy_echo "Running your customizations from ~/.laptop.local ..."
  # shellcheck disable=SC1090
  . "$HOME/.laptop.local"
fi

if ! command -v docker >/dev/null; then
  nohup /Applications/Docker.app/Contents/MacOS/Docker >/dev/null
fi
